### ISSUE TITLE
Can't open qubes menu on the awesome bar (top left)

### ISSUE THREAD

**Issue by shard77** [lorenzohess/qubes-awesomewm-rice#1]
Hey,

I've tried to fork this rice and adjust it to my needs, after reading through your config, I've decided to fetch it without any changes and use it for myself.

I'm encountering an issue where I'm not able to open the qubes menu, when I click on the qubes os icon on the top left, it's not doing anything. Any idea what is causing this issue?

Thanks in advance, and thanks for providing this nice rice!

**Comment by lorenzohess** [comment]
Thanks for opening an issue (the very first!).

Could you be more specific about what is and what isn't happening? Does any type of menu appear when you click the launcher? Does the launcher icon move a bit when you click (as it should?)? If you right-click on the desktop (i.e. wallpaper), the same menu should appear. Does it? This might indicate whether the problem resides with the actual menu or with the launcher.

Have you made any major local changes to your config? How about any changes to the launcher or menu? The Qubes launcher is an `awful.widget.launcher` widget with its `menu` parameter pointing to the menu generated by the `make_menu()` function in `lib/qubes.lua`.

**Comment by shard77** [comment]
Thank you for the prompt response!

No menu appears when I click on the launcher, but the icon does move a little bit. When right-clicking on the desktop, no menu appears. I tried to apply your configuration just by cloning the repository and moving the files to `~/.config/awesome` (so no changes), but I'm encountering the same problem.

Note that I haven't set any wallpaper, but I doubt this would be problematic?
I'm trying to understand why it's not working, the code seems perfectly fine, and I also have everything else working smoothly, as expected. Since your configuration is lightweight, I believe there's no additional stuff to install?

**Comment by lorenzohess** [comment]
Let's consider what parts of `qubes.lua` might be causing the bug, starting with the most likely cause:
1. Can you check for errors in `~/.xsession-errors`? Anything related to `qvm-prefs` or `error: no such domain: '<something>'`? What is the form of the filenames in `~/.config/menus/applications/merged` (the menu is built from the files here)?
2. Are there icon pngs in `/usr/share/icons/hicolor/128x128/devices/`?

Also, make sure you have the `menu_font_family` font installed (variable set in the theme file). The only other dependency (other than fonts) is the `xset` program, but I don't think this should affect the menu.

In general, `~/.xsession-errors` is a good place too look for errors. I don't have a test environment for Qubes, so I can't test the vanilla install. While I've made some local edits and thus am not running the vanilla install right now, going through the git diff doesn't show anything that would seem to affect the menu. Next steps will be to provide instructions for debugging the menu specifically. I'll have to remember how to do that...

EDIT: what version of Qubes OS are you running? What version of Awesome do you have installed? It looks like there were [some changes](https://github.com/QubesOS/updates-status/issues/4402) made to the menu in a recent release of `desktop-linux-awesome`.

**Comment by shard77** [comment]
Hi, thanks for the reply.

I just switched back to another distribution for personal reasons and was about to close this issue, sorry for taking your time!
